---

  #Install extra R libraries.
  - name: Add some R packages.
    command: >
      /home/linuxbrew/.linuxbrew/bin/Rscript --slave --no-save --no-restore-history -e "if (! ('{{ item }}' %in% installed.packages()[,'Package'])) { install.packages(pkgs='{{ item }}', repos=c('http://cran.ms.unimelb.edu.au/')); print('Added'); } else { print('Already installed'); }"
    register: r_result
    failed_when: "r_result.rc != 0 or 'had non-zero exit status' in r_result.stderr"
    changed_when: "'Added' in r_result.stdout"
    with_items:
      - ape
      - getopt
      - Cairo
      - tidyr
    become: yes
    become_user: root

  - name: Add some R packages.
    command: >
      /home/linuxbrew/.linuxbrew/bin/Rscript --slave --no-save --no-restore-history -e "source('http://bioconductor.org/biocLite.R'); if (! ('{{ item }}' %in% installed.packages()[,'Package'])) { biocLite('{{ item }}'); print('Added'); } else { print('Already installed'); }"
    register: b_result
    failed_when: "b_result.rc != 0 or 'had non-zero exit status' in b_result.stderr"
    changed_when: "'Added' in b_result.stdout"
    with_items:
      - limma
      - phyloseq
      - DESeq2
      - edgeR
    become: yes
    become_user: root
    
  #Install extra R libraries.
  - name: Add some R packages.
    command: >
      Rscript --slave --no-save --no-restore-history -e "if (! ('{{ item }}' %in% installed.packages()[,'Package'])) { install.packages(pkgs='{{ item }}', repos=c('http://cran.ms.unimelb.edu.au/')); print('Added'); } else { print('Already installed'); }"
    register: r_result
    failed_when: "r_result.rc != 0 or 'had non-zero exit status' in r_result.stderr"
    changed_when: "'Added' in r_result.stdout"
    with_items:
      - knitr
    become: yes
    become_user: ubuntu
  
  # copy knitr site-library directory from /usr/local/lib/R/site-library/knitr  to /home/linuxbrew/.linuxbrew/lib/R/3.3/site-library
  - name: Copy knitr site-library directory
    copy: src=/usr/local/lib/R/site-library/knitr/ dest=/home/linuxbrew/.linuxbrew/lib/R/3.3/site-library/knitr/
    become: yes
    become_user: root

